Process and PID file

diff --git a/0x05-processes_and_signals/100-process_and_pid_file b/0x05-processes_and_signals/100-process_and_pid_file
--- a/0x05-processes_and_signals/100-process_and_pid_file
+++ b/0x05-processes_and_signals/100-process_and_pid_file
@@ -8,26 +8,27 @@
 #   Deletes the file /var/run/myscript.pid and terminates 
 # itself when receiving a SIGQUIT or SIGTERM signal
 
-touch /var/run/myscript.pid
-pgrep -f 100-process_and_pid_file > /var/run/myscript.pid
+#!/usr/bin/env bash
 
-i=1
-function clean_up()
-{
-    rm /var/run/myscript.pid
+PID_FILE="/var/run/myscript.pid"
+
+# Function to clean up and exit
+clean_up() {
+    echo "I hate the kill command"
+    rm "$PID_FILE"
     exit
 }
-while [[ $i -lt 2 ]];
-    do
-        echo "To infinity and beyond"
-        sleep 2
 
-        trap 'echo "I hate the kill command"' SIGTERM
+# Set trap statements
+trap 'echo "I hate the kill command"' SIGTERM
+trap 'echo "Y U no love me?!"; clean_up' SIGINT
+trap 'clean_up' SIGQUIT SIGTERM
 
-        trap 'echo "Y U no love me?!"' SIGINT
+# Create PID file
+echo $$ > "$PID_FILE"
 
-        trap 'clean_up' SIGQUIT SIGTERM
-
-
-
-    done
+# Infinite loop
+while true; do
+    echo "To infinity and beyond"
+    sleep 2
+done
